### PR TITLE
fixed missing result due to connection closing before access

### PR DESCRIPTION
**Pull request by costastf**

### CODE REVIEW

**Comment by costastf** [comment]
Hi @natcl . Will you tag this with a version so it can be incorporated into Home Assistant easily? Something like 0.9.1 ?

**Comment by costastf** [comment]
@natcl ping. Could you possibly have a look at bumping the tag and packaging?

**Comment by natcl** [comment]
Yes, sorry will do ASAP

**Comment by costastf** [comment]
Thanks a lot!

Regards
Costas

**Comment by natcl** [comment]
New package uploaded, let me know if all is ok !

**Pull request merged**
