### PR TITLE
Added support for sensors.

### PR DESCRIPTION
**Pull request by eldstal**
Sensors can be listed, created and deleted.

Sensors contain a "config" dict and a "state" dict, whose contents are dictated by
the creator of the sensor. These contents can be read and written using phue.

### CODE REVIEW

**Comment by lwis** [comment]
Looks good, any chance of being merged?

**Comment by natcl** [comment]
Done ! I have no sensors to test so I'd be curious to have some feedback on if it works (although everthing looks good)

**Comment by eldstal** [comment]
Same here, actually. I've only tested it with a pretend sensor that TapApp creates to keep its state for Tap buttons to cycle through multiple lighting presets.

This code properly reads and writes to that sensor's state.

Thanks!

**Comment by drtoful** [comment]
Worked for me for getting sensor config and state from a Motion sensor (Model ID: SML001). Thanks for the patch.

**Pull request merged**
