### PR TITLE
add initial scene support

### PR DESCRIPTION
**Pull request by sdague**
The following adds some basic scene support, including a Scene base
object, the ability to list all scenes. The ability to activate a
scence by group_id and scene_id, and a convenience method to activate
a scene based on scene name and group name.

It is intended to be the basis for making automation rules in home
assistant be easier to write.

Addresses https://github.com/studioimaginaire/phue/issues/50

### CODE REVIEW

**Comment by natcl** [comment]
Thanks !

**Comment by DarioBernardo** [comment]
This is no longer working, the property `scene` on the bridge is not working anymore. 
If you do `b.scenes` you'll get 
`    return [Scene(k, **v) for k, v in self.get_scene().items()]
TypeError: __init__() got an unexpected keyword argument 'type'
`
it looks like the scene returns a new parameter `type` that the Scene constructor is not using

**Comment by natcl** [comment]
This works with my setup, can you give more details on your setup, is it with the new version of the Bridge ?

**Comment by Cazfri** [comment]
@DarioBernardo are you using version 1.0 (the version on PyPA via `pip install phue`)? You need to download or clone the source code to get the most recent fixes. The version on PyPA is out of date.

**Comment by DarioBernardo** [comment]
Yes, I have installed phue through pip, so probably that's the problem. I tried to clone the repository and use the script there, but that way I get another problem 
`   return json.loads(decodeString(response))
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes' `
Basically the JSON `loads` function expects a string and instead receive bytes. I am using python 3.4. Should create a new issue for this? thanks

**Comment by natcl** [comment]
What are you calling exactely when this error occurs ?

**Comment by DarioBernardo** [comment]
Hey sorry, the error is still there, unfortunately I haven't been able to look into it further. I'd suggest to do the release and I will try to look into it more one of these weekends. Thanks

**Comment by DarioBernardo** [comment]
Hey, I finally had time to dig into this. Apologies, it was my mistake, as you said, it works with the git version (doesn't work with the pip version). I had a clean installation and it worked, I may have messed up something when i tried the first time. Thanks

**Comment by natcl** [comment]
Thanks for the follow up, will prepare a release then!


--
lecaude.com 
studioimaginaire.com

**Pull request merged**
